### ISSUE TITLE
Tomcat v9.097 download link in Semeru Dockfile failed

### ISSUE THREAD

**Issue by LongyuZhang** [ibmruntimes/ci.docker#160]
In Semeru Container dockfile, the tomcat download link is 
`TOMCAT_DWNLD_URL="https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.97/bin/apache-tomcat-9.0.97.tar.gz";` ([code link](https://github.com/ibmruntimes/semeru-containers/blob/71729987fddf47e141994e027c9b71587cc4bd03/17/jdk/ubi/ubi8/Dockerfile.open.releases.full#L135C23-L135C103))
However this link has expired, the link only offers `v9.0.98` now (https://dlcdn.apache.org/tomcat/tomcat-9/), so the link needs to be updated. Thanks.
FYI @llxia @tajila

**Comment by LongyuZhang** [comment]
As @tajia suggested, may be a stable link can be set for tomcat download in Semeru Dockerfile. @jayasg12 @AdamBrousseau Would you have suggestions about a more stable link? Thanks.

**Comment by AdamBrousseau** [comment]
This issue has come up before from Dockerhub side
https://github.com/docker-library/official-images/pull/17591#issuecomment-2442922629

The ask was to fallback to the archive site if the main site fails.
They have other packages that do this
eg
https://github.com/docker-library/cassandra/blob/1e3d5732f34ceb9e77870d0be9501515f917cc60/5.0/Dockerfile#L107-L118

I think they want a hardcoded version rather than a url that is a generic pointer to "latest". I think this is because they require predictable, repeatable builds.

**Comment by LongyuZhang** [comment]
Based on https://github.com/ibmruntimes/ci.docker/issues/160#issuecomment-2546276201, will try to add a fallback to the archive site to prevent this happens again later.

**Comment by AdamBrousseau** [comment]
On the other hand, having it fail draws our attention to update it. If we fallback to the archive site, how will we monitor for new versions? @jayasg12

**Comment by jayasg12** [comment]
@AdamBrousseau @LongyuZhang Having fallback will not help us, we hit connection issue which made us to pull tomcat from a different site. 
https://github.ibm.com/runtimes/infrastructure/issues/8523

Problem here is the tomcat version which keeps changing and they didn't allow us to have dynamic link which gets the latest version. 
https://github.com/ibmruntimes/semeru-containers/pull/105
https://github.com/docker-library/official-images/pull/16858

Having multistage container image is an option , where as we cannot publish the tomcat image ( as other container image) into official repo with IBM as the maintainer.
